// Code generated by the Encore 1.50.0 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly affiliates: affiliates.ServiceClient
    public readonly analytics: analytics.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly cards: cards.ServiceClient
    public readonly coupons: coupons.ServiceClient
    public readonly moderation: moderation.ServiceClient
    public readonly notifications: notifications.ServiceClient
    public readonly payments: payments.ServiceClient
    public readonly recommendations: recommendations.ServiceClient
    public readonly search: search.ServiceClient
    public readonly storage: storage.ServiceClient
    public readonly subscriptions: subscriptions.ServiceClient
    public readonly users: users.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.affiliates = new affiliates.ServiceClient(base)
        this.analytics = new analytics.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.cards = new cards.ServiceClient(base)
        this.coupons = new coupons.ServiceClient(base)
        this.moderation = new moderation.ServiceClient(base)
        this.notifications = new notifications.ServiceClient(base)
        this.payments = new payments.ServiceClient(base)
        this.recommendations = new recommendations.ServiceClient(base)
        this.search = new search.ServiceClient(base)
        this.storage = new storage.ServiceClient(base)
        this.subscriptions = new subscriptions.ServiceClient(base)
        this.users = new users.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createLink as api_affiliates_manage_links_createLink,
    getCardLinks as api_affiliates_manage_links_getCardLinks,
    getLinkStats as api_affiliates_manage_links_getLinkStats,
    updateLinkStatus as api_affiliates_manage_links_updateLinkStatus
} from "~backend/affiliates/manage_links";
import { trackClick as api_affiliates_track_click_trackClick } from "~backend/affiliates/track_click";
import { trackConversion as api_affiliates_track_conversion_trackConversion } from "~backend/affiliates/track_conversion";

export namespace affiliates {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createLink = this.createLink.bind(this)
            this.getCardLinks = this.getCardLinks.bind(this)
            this.getLinkStats = this.getLinkStats.bind(this)
            this.trackClick = this.trackClick.bind(this)
            this.trackConversion = this.trackConversion.bind(this)
            this.updateLinkStatus = this.updateLinkStatus.bind(this)
        }

        /**
         * Create new affiliate link
         */
        public async createLink(params: RequestType<typeof api_affiliates_manage_links_createLink>): Promise<ResponseType<typeof api_affiliates_manage_links_createLink>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/affiliates/links`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_affiliates_manage_links_createLink>
        }

        /**
         * Get affiliate links for a card
         */
        public async getCardLinks(params: { cardId: number }): Promise<ResponseType<typeof api_affiliates_manage_links_getCardLinks>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/affiliates/links/card/${encodeURIComponent(params.cardId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_affiliates_manage_links_getCardLinks>
        }

        /**
         * Get affiliate link statistics
         */
        public async getLinkStats(params: { linkId: number }): Promise<ResponseType<typeof api_affiliates_manage_links_getLinkStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/affiliates/links/${encodeURIComponent(params.linkId)}/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_affiliates_manage_links_getLinkStats>
        }

        /**
         * Track affiliate click and return redirect URL
         */
        public async trackClick(params: RequestType<typeof api_affiliates_track_click_trackClick>): Promise<ResponseType<typeof api_affiliates_track_click_trackClick>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                referer:      params.referrer,
                "user-agent": params.userAgent,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                affiliateId: params.affiliateId,
                cardId:      params.cardId,
                ipAddress:   params.ipAddress,
                sessionId:   params.sessionId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/affiliates/track-click`, {headers, method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_affiliates_track_click_trackClick>
        }

        /**
         * Track conversion and calculate commission
         */
        public async trackConversion(params: RequestType<typeof api_affiliates_track_conversion_trackConversion>): Promise<ResponseType<typeof api_affiliates_track_conversion_trackConversion>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/affiliates/track-conversion`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_affiliates_track_conversion_trackConversion>
        }

        /**
         * Update affiliate link status
         */
        public async updateLinkStatus(params: RequestType<typeof api_affiliates_manage_links_updateLinkStatus>): Promise<ResponseType<typeof api_affiliates_manage_links_updateLinkStatus>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                isActive: params.isActive,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/affiliates/links/${encodeURIComponent(params.linkId)}/status`, {method: "PATCH", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_affiliates_manage_links_updateLinkStatus>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { dashboard as api_analytics_dashboard_dashboard } from "~backend/analytics/dashboard";
import { trackClick as api_analytics_track_trackClick } from "~backend/analytics/track";

export namespace analytics {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.dashboard = this.dashboard.bind(this)
            this.trackClick = this.trackClick.bind(this)
        }

        /**
         * Get analytics dashboard data (admin only)
         */
        public async dashboard(): Promise<ResponseType<typeof api_analytics_dashboard_dashboard>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/dashboard`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_dashboard_dashboard>
        }

        /**
         * Track affiliate click
         */
        public async trackClick(params: RequestType<typeof api_analytics_track_trackClick>): Promise<ResponseType<typeof api_analytics_track_trackClick>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                referer:      params.referrer,
                "user-agent": params.userAgent,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                affiliateId: params.affiliateId,
                cardId:      params.cardId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/track-click`, {headers, method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_track_trackClick>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { login as api_auth_login_login } from "~backend/auth/login";
import { register as api_auth_register_register } from "~backend/auth/register";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.login = this.login.bind(this)
            this.register = this.register.bind(this)
        }

        /**
         * Login user
         */
        public async login(params: RequestType<typeof api_auth_login_login>): Promise<ResponseType<typeof api_auth_login_login>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/login`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_login_login>
        }

        /**
         * Register a new user
         */
        public async register(params: RequestType<typeof api_auth_register_register>): Promise<ResponseType<typeof api_auth_register_register>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/register`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_register_register>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_cards_create_create } from "~backend/cards/create";
import { get as api_cards_get_get } from "~backend/cards/get";
import { like as api_cards_like_like } from "~backend/cards/like";
import { list as api_cards_list_list } from "~backend/cards/list";

export namespace cards {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.like = this.like.bind(this)
            this.list = this.list.bind(this)
        }

        /**
         * Create a new card (admin only)
         */
        public async create(params: RequestType<typeof api_cards_create_create>): Promise<ResponseType<typeof api_cards_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/cards`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_create_create>
        }

        /**
         * Get card details by slug
         */
        public async get(params: { slug: string }): Promise<ResponseType<typeof api_cards_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/${encodeURIComponent(params.slug)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_get_get>
        }

        /**
         * Like or unlike a card
         */
        public async like(params: { cardId: number }): Promise<ResponseType<typeof api_cards_like_like>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards/${encodeURIComponent(params.cardId)}/like`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_like_like>
        }

        /**
         * Get list of cards with pagination and filtering
         */
        public async list(params: RequestType<typeof api_cards_list_list>): Promise<ResponseType<typeof api_cards_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category: params.category,
                limit:    params.limit === undefined ? undefined : String(params.limit),
                page:     params.page === undefined ? undefined : String(params.page),
                search:   params.search,
                tags:     params.tags,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/cards`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_cards_list_list>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { validate as api_coupons_validate_validate } from "~backend/coupons/validate";

export namespace coupons {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.validate = this.validate.bind(this)
        }

        /**
         * Validate a coupon code
         */
        public async validate(params: RequestType<typeof api_coupons_validate_validate>): Promise<ResponseType<typeof api_coupons_validate_validate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/coupons/validate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_coupons_validate_validate>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    getModerationQueue as api_moderation_queue_getModerationQueue,
    getModerationStats as api_moderation_queue_getModerationStats,
    reviewContent as api_moderation_queue_reviewContent,
    submitForModeration as api_moderation_queue_submitForModeration
} from "~backend/moderation/queue";

export namespace moderation {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getModerationQueue = this.getModerationQueue.bind(this)
            this.getModerationStats = this.getModerationStats.bind(this)
            this.reviewContent = this.reviewContent.bind(this)
            this.submitForModeration = this.submitForModeration.bind(this)
        }

        /**
         * Get moderation queue (admin only)
         */
        public async getModerationQueue(params: RequestType<typeof api_moderation_queue_getModerationQueue>): Promise<ResponseType<typeof api_moderation_queue_getModerationQueue>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                page:   params.page === undefined ? undefined : String(params.page),
                status: params.status === undefined ? undefined : String(params.status),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/moderation/queue`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_moderation_queue_getModerationQueue>
        }

        /**
         * Get moderation statistics
         */
        public async getModerationStats(): Promise<ResponseType<typeof api_moderation_queue_getModerationStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/moderation/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_moderation_queue_getModerationStats>
        }

        /**
         * Review content (admin only)
         */
        public async reviewContent(params: RequestType<typeof api_moderation_queue_reviewContent>): Promise<ResponseType<typeof api_moderation_queue_reviewContent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/moderation/review`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_moderation_queue_reviewContent>
        }

        /**
         * Submit content for moderation
         */
        public async submitForModeration(params: RequestType<typeof api_moderation_queue_submitForModeration>): Promise<ResponseType<typeof api_moderation_queue_submitForModeration>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/moderation/submit`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_moderation_queue_submitForModeration>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    getPreferences as api_notifications_manage_getPreferences,
    getUnreadCount as api_notifications_manage_getUnreadCount,
    getUserNotifications as api_notifications_manage_getUserNotifications,
    markAllAsRead as api_notifications_manage_markAllAsRead,
    markAsRead as api_notifications_manage_markAsRead,
    sendNotification as api_notifications_manage_sendNotification,
    updatePreferences as api_notifications_manage_updatePreferences
} from "~backend/notifications/manage";

export namespace notifications {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getPreferences = this.getPreferences.bind(this)
            this.getUnreadCount = this.getUnreadCount.bind(this)
            this.getUserNotifications = this.getUserNotifications.bind(this)
            this.markAllAsRead = this.markAllAsRead.bind(this)
            this.markAsRead = this.markAsRead.bind(this)
            this.sendNotification = this.sendNotification.bind(this)
            this.updatePreferences = this.updatePreferences.bind(this)
        }

        /**
         * Get/Update notification preferences
         */
        public async getPreferences(): Promise<ResponseType<typeof api_notifications_manage_getPreferences>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/preferences`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_manage_getPreferences>
        }

        /**
         * Get unread notification count
         */
        public async getUnreadCount(): Promise<ResponseType<typeof api_notifications_manage_getUnreadCount>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/unread-count`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_manage_getUnreadCount>
        }

        /**
         * Get user notifications
         */
        public async getUserNotifications(params: RequestType<typeof api_notifications_manage_getUserNotifications>): Promise<ResponseType<typeof api_notifications_manage_getUserNotifications>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
                page:  params.page === undefined ? undefined : String(params.page),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_manage_getUserNotifications>
        }

        /**
         * Mark all notifications as read
         */
        public async markAllAsRead(): Promise<ResponseType<typeof api_notifications_manage_markAllAsRead>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/read-all`, {method: "PATCH", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_manage_markAllAsRead>
        }

        /**
         * Mark notification as read
         */
        public async markAsRead(params: { notificationId: number }): Promise<ResponseType<typeof api_notifications_manage_markAsRead>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/${encodeURIComponent(params.notificationId)}/read`, {method: "PATCH", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_manage_markAsRead>
        }

        /**
         * Send notification to user
         */
        public async sendNotification(params: RequestType<typeof api_notifications_manage_sendNotification>): Promise<ResponseType<typeof api_notifications_manage_sendNotification>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/send`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_manage_sendNotification>
        }

        public async updatePreferences(params: RequestType<typeof api_notifications_manage_updatePreferences>): Promise<ResponseType<typeof api_notifications_manage_updatePreferences>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/preferences`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_manage_updatePreferences>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { checkout as api_payments_checkout_checkout } from "~backend/payments/checkout";
import { webhook as api_payments_webhook_webhook } from "~backend/payments/webhook";

export namespace payments {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.checkout = this.checkout.bind(this)
            this.webhook = this.webhook.bind(this)
        }

        /**
         * Create payment intent for checkout
         */
        public async checkout(params: RequestType<typeof api_payments_checkout_checkout>): Promise<ResponseType<typeof api_payments_checkout_checkout>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/payments/checkout`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payments_checkout_checkout>
        }

        /**
         * Handle Stripe webhooks
         */
        public async webhook(params: RequestType<typeof api_payments_webhook_webhook>): Promise<ResponseType<typeof api_payments_webhook_webhook>> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                "stripe-signature": params.signature,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                body: params.body,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/payments/webhook`, {headers, method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payments_webhook_webhook>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getRecommendations as api_recommendations_generate_getRecommendations } from "~backend/recommendations/generate";
import { trackInteraction as api_recommendations_track_interaction_trackInteraction } from "~backend/recommendations/track_interaction";

export namespace recommendations {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getRecommendations = this.getRecommendations.bind(this)
            this.trackInteraction = this.trackInteraction.bind(this)
        }

        /**
         * Get personalized recommendations for user
         */
        public async getRecommendations(params: RequestType<typeof api_recommendations_generate_getRecommendations>): Promise<ResponseType<typeof api_recommendations_generate_getRecommendations>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
                type:  params.type === undefined ? undefined : String(params.type),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/recommendations`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_recommendations_generate_getRecommendations>
        }

        /**
         * Track user interaction for recommendation engine
         */
        public async trackInteraction(params: RequestType<typeof api_recommendations_track_interaction_trackInteraction>): Promise<ResponseType<typeof api_recommendations_track_interaction_trackInteraction>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/recommendations/track`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_recommendations_track_interaction_trackInteraction>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { advancedSearch as api_search_advanced_search_advancedSearch } from "~backend/search/advanced_search";
import {
    getPopularSearches as api_search_suggestions_getPopularSearches,
    getSuggestions as api_search_suggestions_getSuggestions
} from "~backend/search/suggestions";

export namespace search {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.advancedSearch = this.advancedSearch.bind(this)
            this.getPopularSearches = this.getPopularSearches.bind(this)
            this.getSuggestions = this.getSuggestions.bind(this)
        }

        /**
         * Advanced search with multiple filters and facets
         */
        public async advancedSearch(params: RequestType<typeof api_search_advanced_search_advancedSearch>): Promise<ResponseType<typeof api_search_advanced_search_advancedSearch>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                authorId:   params.authorId === undefined ? undefined : String(params.authorId),
                categories: params.categories?.map((v) => v),
                dateFrom:   params.dateFrom,
                dateTo:     params.dateTo,
                isPremium:  params.isPremium === undefined ? undefined : String(params.isPremium),
                limit:      params.limit === undefined ? undefined : String(params.limit),
                page:       params.page === undefined ? undefined : String(params.page),
                priceMax:   params.priceMax === undefined ? undefined : String(params.priceMax),
                priceMin:   params.priceMin === undefined ? undefined : String(params.priceMin),
                query:      params.query,
                sortBy:     params.sortBy === undefined ? undefined : String(params.sortBy),
                tags:       params.tags?.map((v) => v),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/search/advanced`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_search_advanced_search_advancedSearch>
        }

        /**
         * Get popular search queries
         */
        public async getPopularSearches(): Promise<ResponseType<typeof api_search_suggestions_getPopularSearches>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/search/popular`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_search_suggestions_getPopularSearches>
        }

        /**
         * Get search suggestions for autocomplete
         */
        public async getSuggestions(params: RequestType<typeof api_search_suggestions_getSuggestions>): Promise<ResponseType<typeof api_search_suggestions_getSuggestions>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                query: params.query,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/search/suggestions`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_search_suggestions_getSuggestions>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getUploadUrl as api_storage_upload_getUploadUrl } from "~backend/storage/upload";

export namespace storage {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getUploadUrl = this.getUploadUrl.bind(this)
        }

        /**
         * Generate signed upload URL for admin uploads
         */
        public async getUploadUrl(params: RequestType<typeof api_storage_upload_getUploadUrl>): Promise<ResponseType<typeof api_storage_upload_getUploadUrl>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/storage/upload-url`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_storage_upload_getUploadUrl>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    cancelSubscription as api_subscriptions_manage_cancelSubscription,
    getUsage as api_subscriptions_manage_getUsage,
    getUserSubscription as api_subscriptions_manage_getUserSubscription,
    subscribe as api_subscriptions_manage_subscribe
} from "~backend/subscriptions/manage";
import {
    createPlan as api_subscriptions_plans_createPlan,
    getPlans as api_subscriptions_plans_getPlans,
    updatePlan as api_subscriptions_plans_updatePlan
} from "~backend/subscriptions/plans";

export namespace subscriptions {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.cancelSubscription = this.cancelSubscription.bind(this)
            this.createPlan = this.createPlan.bind(this)
            this.getPlans = this.getPlans.bind(this)
            this.getUsage = this.getUsage.bind(this)
            this.getUserSubscription = this.getUserSubscription.bind(this)
            this.subscribe = this.subscribe.bind(this)
            this.updatePlan = this.updatePlan.bind(this)
        }

        /**
         * Cancel subscription
         */
        public async cancelSubscription(params: RequestType<typeof api_subscriptions_manage_cancelSubscription>): Promise<ResponseType<typeof api_subscriptions_manage_cancelSubscription>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/subscriptions/cancel`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_subscriptions_manage_cancelSubscription>
        }

        /**
         * Create new subscription plan (admin only)
         */
        public async createPlan(params: RequestType<typeof api_subscriptions_plans_createPlan>): Promise<ResponseType<typeof api_subscriptions_plans_createPlan>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/subscriptions/plans`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_subscriptions_plans_createPlan>
        }

        /**
         * Get all active subscription plans
         */
        public async getPlans(): Promise<ResponseType<typeof api_subscriptions_plans_getPlans>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/subscriptions/plans`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_subscriptions_plans_getPlans>
        }

        /**
         * Get subscription usage
         */
        public async getUsage(): Promise<ResponseType<typeof api_subscriptions_manage_getUsage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/subscriptions/usage`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_subscriptions_manage_getUsage>
        }

        /**
         * Get user's current subscription
         */
        public async getUserSubscription(): Promise<ResponseType<typeof api_subscriptions_manage_getUserSubscription>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/subscriptions/current`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_subscriptions_manage_getUserSubscription>
        }

        /**
         * Subscribe to a plan
         */
        public async subscribe(params: RequestType<typeof api_subscriptions_manage_subscribe>): Promise<ResponseType<typeof api_subscriptions_manage_subscribe>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/subscriptions/subscribe`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_subscriptions_manage_subscribe>
        }

        /**
         * Update subscription plan
         */
        public async updatePlan(params: RequestType<typeof api_subscriptions_plans_updatePlan>): Promise<ResponseType<typeof api_subscriptions_plans_updatePlan>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                billingPeriod: params.billingPeriod,
                description:   params.description,
                features:      params.features,
                maxDownloads:  params.maxDownloads,
                name:          params.name,
                price:         params.price,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/subscriptions/plans/${encodeURIComponent(params.planId)}`, {method: "PATCH", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_subscriptions_plans_updatePlan>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { bookmark as api_users_bookmark_bookmark } from "~backend/users/bookmark";
import { bookmarks as api_users_bookmarks_bookmarks } from "~backend/users/bookmarks";
import { profile as api_users_profile_profile } from "~backend/users/profile";

export namespace users {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.bookmark = this.bookmark.bind(this)
            this.bookmarks = this.bookmarks.bind(this)
            this.profile = this.profile.bind(this)
        }

        /**
         * Bookmark or unbookmark a card
         */
        public async bookmark(params: { cardId: number }): Promise<ResponseType<typeof api_users_bookmark_bookmark>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/user/bookmark/${encodeURIComponent(params.cardId)}`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_bookmark_bookmark>
        }

        /**
         * Get user's bookmarked cards
         */
        public async bookmarks(params: RequestType<typeof api_users_bookmarks_bookmarks>): Promise<ResponseType<typeof api_users_bookmarks_bookmarks>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
                page:  params.page === undefined ? undefined : String(params.page),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/user/bookmarks`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_bookmarks_bookmarks>
        }

        /**
         * Get user profile
         */
        public async profile(): Promise<ResponseType<typeof api_users_profile_profile>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/user/profile`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_profile_profile>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.50.0)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
